name: Latest blog posts

on:
  schedule:
    - cron: '0 0 * * *' # run once a day
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_url: https://medium.com/feed/@ancestor.profzoom    # Replace with your actual RSS feed URL
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          filter_by_content_length: 500
          # For Medium: 'https://medium.com/feed/@your-username'
          # For Dev.to: 'https://dev.to/feed/your-username'
          # For personal blog: 'https://your-blog.com/rss.xml'
